#!/bin/bash
# MySQL to Postgres SQL transformation script
# Converts MySQL dump files to Postgres-compatible SQL
# Usage: ./mysql-to-postgres-transform.sh <input_mysql.sql> <output_postgres.sql>

set -e

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <input_mysql.sql> <output_postgres.sql>"
    exit 1
fi

INPUT_FILE="$1"
OUTPUT_FILE="$2"

if [ ! -f "$INPUT_FILE" ]; then
    echo "Error: Input file '$INPUT_FILE' not found"
    exit 1
fi

echo "Transforming MySQL dump to Postgres-compatible SQL..."
echo "Input: $INPUT_FILE"
echo "Output: $OUTPUT_FILE"

# Create a temporary file for intermediate processing
TEMP_FILE=$(mktemp)

# Step 1: Copy input to temp file
cp "$INPUT_FILE" "$TEMP_FILE"

# Step 2: Remove MySQL-specific syntax
echo "Removing MySQL-specific syntax..."

# Remove MySQL dump headers and settings
sed -i '/^\/\*!40101 SET @OLD_CHARACTER_SET_CLIENT/d' "$TEMP_FILE"
sed -i '/^\/\*!40101 SET @OLD_CHARACTER_SET_RESULTS/d' "$TEMP_FILE"
sed -i '/^\/\*!40101 SET @OLD_COLLATION_CONNECTION/d' "$TEMP_FILE"
sed -i '/^\/\*!40103 SET @OLD_TIME_ZONE/d' "$TEMP_FILE"
sed -i '/^\/\*!40103 SET TIME_ZONE/d' "$TEMP_FILE"
sed -i '/^\/\*!40014 SET @OLD_UNIQUE_CHECKS/d' "$TEMP_FILE"
sed -i '/^\/\*!40014 SET UNIQUE_CHECKS/d' "$TEMP_FILE"
sed -i '/^\/\*!40014 SET @OLD_FOREIGN_KEY_CHECKS/d' "$TEMP_FILE"
sed -i '/^\/\*!40014 SET FOREIGN_KEY_CHECKS/d' "$TEMP_FILE"
sed -i '/^\/\*!40101 SET @OLD_SQL_MODE/d' "$TEMP_FILE"
sed -i '/^\/\*!40101 SET SQL_MODE/d' "$TEMP_FILE"
sed -i '/^\/\*!40111 SET @OLD_SQL_NOTES/d' "$TEMP_FILE"
sed -i '/^\/\*!40111 SET SQL_NOTES/d' "$TEMP_FILE"

# Remove ENGINE=InnoDB
sed -i 's/ ENGINE=InnoDB//g' "$TEMP_FILE"

# Remove DEFAULT CHARSET and COLLATE
sed -i 's/ DEFAULT CHARSET=[a-zA-Z0-9_]*//g' "$TEMP_FILE"
sed -i 's/ COLLATE=[a-zA-Z0-9_]*//g' "$TEMP_FILE"

# Remove AUTO_INCREMENT specifications
sed -i 's/ AUTO_INCREMENT=[0-9]*//g' "$TEMP_FILE"

# Step 3: Transform data types
echo "Transforming data types..."

# Replace backticks with double quotes for identifiers
sed -i 's/`/"/g' "$TEMP_FILE"

# Replace TINYINT(1) with BOOLEAN
sed -i 's/ tinyint(1)/ boolean/g' "$TEMP_FILE"
sed -i 's/ TINYINT(1)/ BOOLEAN/g' "$TEMP_FILE"

# Replace TINYINT with SMALLINT
sed -i 's/ tinyint/ smallint/g' "$TEMP_FILE"
sed -i 's/ TINYINT/ SMALLINT/g' "$TEMP_FILE"

# Replace DATETIME with TIMESTAMP
sed -i 's/ datetime(6)/ timestamp(6)/g' "$TEMP_FILE"
sed -i 's/ datetime/ timestamp/g' "$TEMP_FILE"
sed -i 's/ DATETIME(6)/ TIMESTAMP(6)/g' "$TEMP_FILE"
sed -i 's/ DATETIME/ TIMESTAMP/g' "$TEMP_FILE"

# Replace LONGTEXT with TEXT
sed -i 's/ longtext/ text/g' "$TEMP_FILE"
sed -i 's/ LONGTEXT/ TEXT/g' "$TEMP_FILE"

# Step 4: Handle ON UPDATE CURRENT_TIMESTAMP
echo "Handling timestamp auto-update syntax..."
sed -i 's/ ON UPDATE CURRENT_TIMESTAMP(6)//g' "$TEMP_FILE"
sed -i 's/ ON UPDATE CURRENT_TIMESTAMP//g' "$TEMP_FILE"
sed -i 's/ on update CURRENT_TIMESTAMP(6)//g' "$TEMP_FILE"
sed -i 's/ on update CURRENT_TIMESTAMP//g' "$TEMP_FILE"

# Step 5: Fix DEFAULT CURRENT_TIMESTAMP syntax
sed -i 's/DEFAULT CURRENT_TIMESTAMP(6)/DEFAULT CURRENT_TIMESTAMP/g' "$TEMP_FILE"

# Step 6: Handle UNSIGNED integers
echo "Handling UNSIGNED integers..."
sed -i 's/ unsigned//g' "$TEMP_FILE"
sed -i 's/ UNSIGNED//g' "$TEMP_FILE"

# Step 7: Add Postgres-specific headers
echo "Adding Postgres-specific configuration..."
cat > "$OUTPUT_FILE" << 'EOF'
-- PostgreSQL dump converted from MySQL
-- Generated by mysql-to-postgres-transform.sh

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Disable triggers during import for performance
SET session_replication_role = 'replica';

EOF

# Append transformed content
cat "$TEMP_FILE" >> "$OUTPUT_FILE"

# Add footer to re-enable triggers
cat >> "$OUTPUT_FILE" << 'EOF'

-- Re-enable triggers
SET session_replication_role = 'origin';
EOF

# Clean up
rm "$TEMP_FILE"

echo "Transformation complete!"
echo "Output saved to: $OUTPUT_FILE"
echo ""
echo "IMPORTANT NOTES:"
echo "1. Review the output file for any remaining MySQL-specific syntax"
echo "2. Postgres does not support 'ON UPDATE CURRENT_TIMESTAMP' - consider using triggers if needed"
echo "3. Test the import on a staging database before production"
echo "4. Verify data types are correctly transformed"
