#!/bin/bash

# Base directory: the location of the script
BASE_DIR="$(dirname "$(realpath "$0")")"

# Source environment variables from .env file relative to the script's location
. "$BASE_DIR/.env"

# Shared configuration
EXIT_STATUS=0
MYSQL_USER="root"
MYSQL_PASSWORD="${MYSQL_ROOT_PASSWORD}"
MYSQL_DATABASE="${MYSQL_DATABASE}"
MYSQL_CONTAINER="alkemio_dev_mysql"
AUDIT_TABLE="user_authid_backfill_audit"
ARTIFACT_DIR="$BASE_DIR/artifacts"
AUDIT_CSV_ARTIFACT="${ARTIFACT_DIR}/user_authid_backfill_audit.csv"
AUDIT_SUMMARY_ARTIFACT="${ARTIFACT_DIR}/user_authid_backfill_summary.json"

mkdir -p "$ARTIFACT_DIR"

# Helper to capture audit table artifacts & metrics
capture_authid_audit() {
    # Determine if the audit table exists before querying
    local table_exists
    table_exists=$(docker exec -i "$MYSQL_CONTAINER" mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" -N -B \
        -e "SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA='${MYSQL_DATABASE}' AND TABLE_NAME='${AUDIT_TABLE}';" 2>/dev/null)

    if [[ -z "$table_exists" || "$table_exists" -eq 0 ]]; then
        echo "AuthId backfill audit table not found; skipping artifact capture."
        echo '{}' > "$AUDIT_SUMMARY_ARTIFACT"
        return
    fi

    # Copy CSV artifact generated by export script when available
    local audit_container_path="/var/lib/mysql-files/CSVs/${AUDIT_TABLE}.csv"
    if docker exec "$MYSQL_CONTAINER" bash -c "test -f '$audit_container_path'" 2>/dev/null; then
        docker cp "$MYSQL_CONTAINER:$audit_container_path" "$AUDIT_CSV_ARTIFACT" 2>/dev/null || \
            echo "Warning: failed to copy audit CSV artifact." >&2
    else
        echo "Audit CSV export not found; ensure export_to_csv.sh includes ${AUDIT_TABLE}."
    fi

    local status_counts
    status_counts=$(docker exec -i "$MYSQL_CONTAINER" mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" -N -B \
        -e "SELECT status, COUNT(*) FROM ${AUDIT_TABLE} GROUP BY status;" "$MYSQL_DATABASE" 2>/dev/null)

    if [[ -z "$status_counts" ]]; then
        echo "AuthId Backfill Audit Summary: no audit rows recorded."
        echo '{}' > "$AUDIT_SUMMARY_ARTIFACT"
        return
    fi

    echo "AuthId Backfill Audit Summary:"
    echo '{' > "$AUDIT_SUMMARY_ARTIFACT"
    local first_entry=1

    while IFS=$'\t' read -r status count; do
        [[ -z "$status" ]] && continue

        echo "  - status=${status} count=${count}"
        echo "metric.authid_backfill_${status}=${count}"

        if [[ $first_entry -eq 0 ]]; then
            printf ',\n' >> "$AUDIT_SUMMARY_ARTIFACT"
        fi
        printf '  "%s": %s' "$status" "$count" >> "$AUDIT_SUMMARY_ARTIFACT"
        first_entry=0

        if [[ "$status" == "error" && "$count" -gt 0 ]]; then
            echo "Detected ${count} authId migration error record(s)." >&2
            docker exec -i "$MYSQL_CONTAINER" mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" \
                -e "SELECT userId, email, identityId, detail FROM ${AUDIT_TABLE} WHERE status='error';" "$MYSQL_DATABASE" >&2
            EXIT_STATUS=1
        fi
    done <<< "$status_counts"

    printf '\n}\n' >> "$AUDIT_SUMMARY_ARTIFACT"
}

# Back database up
bash "$BASE_DIR/create_snapshot.sh" "backup.sql"

# Restore the reference schema
bash "$BASE_DIR/restore_snapshot.sh" "db/reference_schema.sql"

# Run the migration and wait for completion
pnpm run migration:run

# Check the exit status of the command
migration_status=$?

if [[ $migration_status -eq 0 ]]; then
    echo "Migration completed successfully."
    # Export the migrated CSVs to
    bash "$BASE_DIR/export_to_csv.sh"

    capture_authid_audit

    # Compare the migrated CSVs to the reference CSVs
    bash "$BASE_DIR/compare_sql_tables.sh"
else
    echo "Migration failed."
    EXIT_STATUS=1
fi

# Restore backup
bash "$BASE_DIR/restore_snapshot.sh" "backup.sql"

rm "$BASE_DIR/backup.sql"

exit $EXIT_STATUS