component_depth: 4
default_excludes: true
languages:
  - typescript
  - javascript
  - script
exclude:
  - /src/migrations/.*
  - /src/common/scalars/.*
  - /src/core/bootstrap/.*
  - /src/core/middleware/.*
  - /src/common/decorators/.*
  - /src/utils/logging/.*
  - /src/domain/common/interfaces/.*
  - /src/config/.*
  - /.scripts/.*
  - /.build/.*
  - /src/services/platform/configuration/templates/.*
  - .*/*.resolver.*
  - .*/*.entity.*
  - .*/*.dto.*
  - .*/*.exception.*
