version: '3.7'

networks:
  ct_server_dev:
  ct_dev_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1

volumes:
  ct_server_dev:
  ct_server_dev_db:

services:
  db:
    container_name: ct_server_dev_db
    image: mysql:8.0.11
    networks:
      - ct_dev_net
    command: --default-authentication-plugin=mysql_native_password --init-file /bootstrap_scripts/1.sql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ct_server_dev_db:/var/lib/mysql
      - ./.scripts/schema.sql:/bootstrap_scripts/1.sql

  ct_ipfs_server:
    container_name: ct_ipfs_server
    image: ipfs/go-ipfs
    networks:
      - ct_dev_net
    restart: always
    ports:
      - 4001:4001/tcp
      - 4002:4002/udp
      - 5001:5001
      - 8080:8080
    volumes:
      - /tmp/ipfs-docker-data:/data/ipfs

  kratos-migrate:
    image: oryd/kratos:v0.6.1-alpha.1
    environment:
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(${DATABASE_HOST}:3306)/kratos?max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./.build/ory/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - ct_dev_net

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.6.1-alpha.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(${DATABASE_HOST}:3306)/kratos?max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
      - SERVE_PUBLIC_BASE_URL=http://localhost:4455/.ory/kratos/public/
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./.build/ory/kratos/email-password
        target: /etc/config/kratos
    networks:
      - ct_dev_net

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - ct_dev_net

  oathkeeper:
    image: oryd/oathkeeper:v0.38
    depends_on:
      - kratos
    ports:
      - 4455:4455
      - 4456:4456
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - ct_dev_net
    volumes:
      - ./.build/ory/oathkeeper:/etc/config/oathkeeper
