version: '3.7'

volumes:
  alkemio_dev_mysql_db:
  rabbitmq_data:
    driver: local

networks:
  alkemio_dev_net:

services:
  traefik:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_traefik
    image: traefik:v2.4.9
    restart: always
    ports:
      - 8888:8080
      - 8088:8088
      - 3000:80
      - 3306:3306
      - 8008:8008
      - 5001:5001
      - 4436:4436
      - 4437:4437
      - 5672:5672
      - 15672:15672
    networks:
      - alkemio_dev_net
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ./.build/traefik/
        target: /etc/traefik/

  mysql_db:
    container_name: alkemio_dev_mysql_db
    image: mysql:8.0.11
    networks:
      - alkemio_dev_net
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    restart: always
    ports:
      - 3306
    volumes:
      - alkemio_dev_mysql_db:/var/lib/mysql
      - ./.scripts/schema.sql:/bootstrap_scripts/1.sql
    command: --default-authentication-plugin=mysql_native_password --init-file /bootstrap_scripts/1.sql

  kratos-migrate:
    container_name: alkemio_dev_kratos_migrate
    image: oryd/kratos:v0.8.0-alpha.3
    depends_on:
      - mysql_db
    environment:
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(${DATABASE_HOST}:3306)/kratos?max_conns=20&max_idle_conns=4
    restart: on-failure
    networks:
      - alkemio_dev_net
    volumes:
      - type: bind
        source: ./.build/ory/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos:
    container_name: alkemio_dev_kratos
    image: oryd/kratos:v0.8.0-alpha.3
    depends_on:
      - kratos-migrate
    ports:
      - 4433
      - 4434
    restart: unless-stopped
    environment:
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(${DATABASE_HOST}:3306)/kratos?max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    networks:
      - alkemio_dev_net
    volumes:
      - type: bind
        source: ./.build/ory/kratos/email-password
        target: /etc/config/kratos
      - type: bind
        source: ./.build/ory/kratos/courier-templates
        target: /etc/config/kratos/courier-templates
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  oathkeeper:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_oathkeeper
    image: oryd/oathkeeper:v0.38.9-beta.1
    restart: always
    depends_on:
      - kratos
    ports:
      - 4455
      - 4456
    environment:
      - LOG_LEVEL=debug
    networks:
      - alkemio_dev_net
    volumes:
      - ./.build/ory/oathkeeper:/etc/config/oathkeeper
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"

  mailslurper:
    container_name: alkemio_dev_kratos_mailslurper
    image: oryd/mailslurper:latest-smtps
    restart: always
    ports:
      - 4436
      - 4437
    networks:
      - alkemio_dev_net

  ipfs:
    container_name: alkemio_dev_ipfs
    image: ipfs/go-ipfs:v0.9.1
    networks:
      - alkemio_dev_net
    restart: always
    ports:
      - 4001
      - 4002
      - 5001
      - 8080
    volumes:
      - /tmp/ipfs-docker-data:/data/ipfs

  synapse:
    container_name: alkemio_dev_synapse
    image: matrixdotorg/synapse:v1.39.0
    restart: always
    environment:
      - SYNAPSE_NO_TLS=true
      - SYNAPSE_ENABLE_REGISTRATION=true
      - SYNAPSE_HOMESERVER_NAME
      - SYNAPSE_SERVER_URL
      - SYNAPSE_SERVER_SHARED_SECRET
    networks:
      - alkemio_dev_net
    ports:
      - 8008
    volumes:
      - type: bind
        source: ./.build/synapse
        target: /data

  synapse-admin:
    container_name: alkemio_dev_synapse_admin
    hostname: synapse-admin
    image: awesometechnologies/synapse-admin:0.8.1
    restart: always
    networks:
      - alkemio_dev_net
    ports:
      - 80

  rabbitmq:
    container_name: alkemio_dev_rabbitmq
    image: docker.io/bitnami/rabbitmq:3.9
    restart: always
    networks:
      - alkemio_dev_net
    ports:
      - 4369
      - 5672
      - 25672
      - 15672
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
    volumes:
      - 'rabbitmq_data:/bitnami'

  notification:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_notifications
    hostname: notifications
    image: alkemio/notifications:v0.4.5
    environment:
      - RABBITMQ_HOST
      - LOGGING_CONSOLE_ENABLED
      - LOGGING_LEVEL_CONSOLE
      - EMAIL_SMTP_HOST
      - EMAIL_MULTI_PROVIDER_STRATEGY
      - ENVIRONMENT=dev
      - ALKEMIO_SERVER_ENDPOINT
      - ALKEMIO_WEBCLIENT_ENDPOINT
      - KRATOS_API_PUBLIC_ENDPOINT
      - SERVICE_ACCOUNT_USERNAME
      - SERVICE_ACCOUNT_PASSWORD
      - WAIT_HOSTS=host.docker.internal:4000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    restart: always
    networks:
      - alkemio_dev_net
    command: sh -c "/wait && npm run start"

  wallet-manager:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_wallet_manager
    hostname: wallet-manager
    image: alkemio/wallet-manager:v0.3.0
    environment:
      - DATABASE_HOST
      - MYSQL_ROOT_PASSWORD
      - RABBITMQ_HOST
      - LOGGING_CONSOLE_ENABLED
      - LOGGING_LEVEL_CONSOLE
      - ENVIRONMENT=dev
      - WAIT_HOSTS=host.docker.internal:4000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    restart: always
    networks:
      - alkemio_dev_net
    command: sh -c "/wait && npm run start"
