version: '3.7'

volumes:
  alkemio_dev_mysql:
  alkemio_dev_postgres:
  tmpvolume:
  rabbitmq_data:
    driver: local
  alkemio_dev_synapse:

networks:
  alkemio_dev_net:

services:
  traefik:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_traefik
    image: traefik:v2.9.6
    restart: always
    ports:
      - 8888:8080
      - 8088:8088
      - 3000:80
      - 3306:3306
      - 5432:5432
      - 8008:8008
      - 5001:5001
      - 4436:4436
      - 4437:4437
      - 1025:1025
      - 5672:5672
      - 15672:15672
      - 6379:6379
    networks:
      - alkemio_dev_net
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ./.build/traefik/
        target: /etc/traefik/

  mysql:
    container_name: alkemio_dev_mysql
    image: mysql:8.3.0
    networks:
      - alkemio_dev_net
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    restart: always
    ports:
      - 3306
    volumes:
      - alkemio_dev_mysql:/var/lib/mysql
      - ./.scripts/schema.sql:/bootstrap_scripts/1.sql
      - ./.scripts/migrations/CSVs:/tmp/CSVs
      - tmpvolume:/tmp
    command: --sql_mode="" --default-authentication-plugin=mysql_native_password --init-file /bootstrap_scripts/1.sql

  kratos-migrate:
    container_name: alkemio_dev_kratos_migrate
    image: oryd/kratos:v1.3.1
    depends_on:
      - mysql
    environment:
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(${DATABASE_HOST}:3306)/kratos?max_conns=20&max_idle_conns=4
    restart: on-failure
    networks:
      - alkemio_dev_net
    volumes:
      - type: bind
        source: ./.build/ory/kratos
        target: /etc/config/kratos
      - type: bind
        source: ../kratos
        target: /dockerdev
        read_only: false
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos:
    container_name: alkemio_dev_kratos
    build:
      context: ../kratos
      dockerfile: ../kratos/.docker/Dockerfile-debug
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
    ports:
      - 4433
      - 4434
      - 9999:40000
    restart: unless-stopped
    environment:
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(${DATABASE_HOST}:3306)/kratos?max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    networks:
      - alkemio_dev_net
    volumes:
      - type: bind
        source: ./.build/ory/kratos
        target: /etc/config/kratos
      - type: bind
        source: ../kratos
        target: /dockerdev
        read_only: false
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  hydra-migrate:
    container_name: alkemio_dev_hydra_migrate
    image: oryd/hydra:v2.2.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate sql -e --yes
    networks:
      - alkemio_dev_net
    restart: on-failure

  hydra:
    container_name: alkemio_dev_hydra
    image: oryd/hydra:v2.2.0
    depends_on:
      hydra-migrate:
        condition: service_completed_successfully
    ports:
      - 4444
      - 4445
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4&max_conn_lifetime=30m&max_conn_idle_time=5m
      - SECRETS_SYSTEM=${HYDRA_SYSTEM_SECRET}
      - URLS_SELF_PUBLIC=${HYDRA_PUBLIC_URL}/
      - URLS_SELF_ISSUER=${HYDRA_PUBLIC_URL}/
      - URLS_LOGIN=${HYDRA_PUBLIC_URL}/oidc/login
      - URLS_CONSENT=${HYDRA_PUBLIC_URL}/oidc/consent
      - URLS_SELF_ADMIN=http://hydra:4445/
      - SERVE_PUBLIC_CORS_ENABLED=true
      - SERVE_ADMIN_CORS_ENABLED=true
      - OAUTH2_ALLOWED_TOP_LEVEL_CLAIMS=email,email_verified,given_name,family_name
      - LOG_LEVEL=debug
    command: serve all --dev
    networks:
      - alkemio_dev_net
    restart: unless-stopped

  hydra-client-setup:
    container_name: alkemio_dev_hydra_client_setup
    image: curlimages/curl:8.1.2
    depends_on:
      - hydra
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
      - SYNAPSE_OIDC_CLIENT_ID
      - SYNAPSE_OIDC_CLIENT_SECRET
      - SYNAPSE_ADMIN_URL
      - SYNAPSE_PUBLIC_URL
    networks:
      - alkemio_dev_net
    restart: on-failure
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Waiting for Hydra to be ready..."
        until curl -sf $$HYDRA_ADMIN_URL/health/ready > /dev/null 2>&1; do
          echo "Hydra not ready yet, waiting..."
          sleep 2
        done
        echo "Hydra is ready, checking if client exists..."

        # Check if client already exists
        if curl -sf $$HYDRA_ADMIN_URL/admin/clients/$$SYNAPSE_OIDC_CLIENT_ID > /dev/null 2>&1; then
          echo "Client $$SYNAPSE_OIDC_CLIENT_ID already exists, updating it..."
          curl -X PUT $$HYDRA_ADMIN_URL/admin/clients/$$SYNAPSE_OIDC_CLIENT_ID \
            -H "Content-Type: application/json" \
            -d "{
              \"client_id\": \"$$SYNAPSE_OIDC_CLIENT_ID\",
              \"client_name\": \"Synapse Matrix Server\",
              \"client_secret\": \"$$SYNAPSE_OIDC_CLIENT_SECRET\",
              \"grant_types\": [\"authorization_code\", \"refresh_token\"],
              \"response_types\": [\"code\"],
              \"redirect_uris\": [\"$$SYNAPSE_PUBLIC_URL/_synapse/client/oidc/callback\"],
              \"scope\": \"openid profile email\",
              \"token_endpoint_auth_method\": \"client_secret_basic\"
            }"
          echo "Client updated successfully"
          exit 0
        fi

        echo "Registering Synapse OAuth2 client..."
        curl -X POST $$HYDRA_ADMIN_URL/admin/clients \
          -H "Content-Type: application/json" \
          -d "{
            \"client_id\": \"$$SYNAPSE_OIDC_CLIENT_ID\",
            \"client_name\": \"Synapse Matrix Server\",
            \"client_secret\": \"$$SYNAPSE_OIDC_CLIENT_SECRET\",
            \"grant_types\": [\"authorization_code\", \"refresh_token\"],
            \"response_types\": [\"code\"],
            \"redirect_uris\": [\"$$SYNAPSE_PUBLIC_URL/_synapse/client/oidc/callback\"],
            \"scope\": \"openid profile email\",
            \"token_endpoint_auth_method\": \"client_secret_basic\"
          }"

        if [ $$? -eq 0 ]; then
          echo "Successfully registered Synapse OAuth2 client"
        else
          echo "Failed to register client"
          exit 1
        fi

  oidc-service:
    container_name: alkemio_dev_oidc_service
    image: docker.io/alkemio/oidc-service:v0.6.0
    platform: linux/amd64
    depends_on:
      - hydra
      - kratos
    environment:
      - OIDC_ALLOW_INSECURE_HTTP=true
      - OIDC_HYDRA_ADMIN_URL
      - OIDC_KRATOS_ADMIN_URL
      - OIDC_KRATOS_PUBLIC_URL
      - OIDC_KRATOS_BROWSER_URL=http://localhost:3000/ory/kratos/public
      - OIDC_WEB_BASE_URL=http://localhost:3000
    networks:
      - alkemio_dev_net
    ports:
      - 8080
    restart: unless-stopped

  oathkeeper:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_oathkeeper
    image: oryd/oathkeeper:v0.38.19-beta.1
    restart: always
    depends_on:
      - kratos
    ports:
      - 4455
      - 4456
    environment:
      - LOG_LEVEL=debug
    networks:
      - alkemio_dev_net
    volumes:
      - ./.build/ory/oathkeeper:/etc/config/oathkeeper
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"

  mailslurper:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_kratos_mailslurper
    image: oryd/mailslurper:latest-smtps
    restart: always
    ports:
      - 4436
      - 4437
      - 1025
    networks:
      - alkemio_dev_net

  synapse:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_synapse
    image: matrixdotorg/synapse:v1.132.0
    depends_on:
      - postgres
    restart: always
    environment:
      - SYNAPSE_NO_TLS=true
      - SYNAPSE_ENABLE_REGISTRATION=true
      - SYNAPSE_HOMESERVER_NAME
      - SYNAPSE_SERVER_URL
      - SYNAPSE_SERVER_SHARED_SECRET
    networks:
      - alkemio_dev_net
    ports:
      - 8008
    volumes:
      - type: bind
        source: ./.build/synapse
        target: /data
      - type: volume
        source: alkemio_dev_synapse
        target: /data/keys
        read_only: false

  postgres:
    container_name: alkemio_dev_postgres
    image: postgres:17.5
    networks:
      - alkemio_dev_net
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C --lc-ctype=C
      - POSTGRES_MULTIPLE_DATABASES
    restart: always
    ports:
      - 5432
    volumes:
      - alkemio_dev_postgres:/var/lib/postgresql/data
      - ./.build/postgres/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    healthcheck:
      test: >
        bash -c "databases=\"$$POSTGRES_DB,$$POSTGRES_MULTIPLE_DATABASES\"; for db in $$(echo \"$$databases\" | tr ',' ' '); do [ -z \"$$db\" ] && continue; pg_isready -U \"$$POSTGRES_USER\" -d \"$$db\" -h localhost || exit 1; done"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  synapse-admin:
    container_name: alkemio_dev_synapse_admin
    hostname: synapse-admin
    image: awesometechnologies/synapse-admin:0.8.1
    restart: always
    networks:
      - alkemio_dev_net
    ports:
      - 80

  rabbitmq:
    container_name: alkemio_dev_rabbitmq
    image: rabbitmq:3.9.13-management
    restart: always
    networks:
      - alkemio_dev_net
    ports:
      - 5672
      - 15672
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_DEFAULT_USER=alkemio-admin
      - RABBITMQ_DEFAULT_PASS=alkemio!
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    command:
      [
        'bash',
        '-c',
        'chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server --hostname rmq',
      ]

  notification:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_notifications
    hostname: notifications
    image: alkemio/notifications:v0.27.0
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - LOGGING_CONSOLE_ENABLED
      - LOGGING_LEVEL_CONSOLE
      - EMAIL_SMTP_HOST
      - EMAIL_MULTI_PROVIDER_STRATEGY
      - EMAIL_SMTP_SECURE
      - EMAIL_SMTP_PORT
      - EMAIL_SMTP_USER
      - EMAIL_SMTP_PASSWORD
      - ENVIRONMENT=dev
      - ALKEMIO_SERVER_ENDPOINT
      - ALKEMIO_WEBCLIENT_ENDPOINT
      - KRATOS_API_PUBLIC_ENDPOINT
      - SERVICE_ACCOUNT_USERNAME
      - SERVICE_ACCOUNT_PASSWORD
      - WAIT_HOSTS=host.docker.internal:3000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - EMAIL_FROM
      - EMAIL_FROM_NAME
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - alkemio_dev_net
    command: sh -c "/wait && npm run start"

  matrix-adapter:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_matrix_adapter
    hostname: matrix-adapter
    image: alkemio/matrix-adapter:v0.7.2
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - SYNAPSE_HOMESERVER_NAME
      - SYNAPSE_SERVER_URL
      - SYNAPSE_SERVER_SHARED_SECRET
      - SYNAPSE_SERVER_NAME
      - LOGGING_CONSOLE_ENABLED
      - LOGGING_LEVEL_CONSOLE
      - ENVIRONMENT=dev
      - WAIT_HOSTS=host.docker.internal:3000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    restart: always
    networks:
      - alkemio_dev_net
    command: sh -c "/wait && npm run start"

  wallet-manager:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_wallet_manager
    hostname: wallet-manager
    image: alkemio/wallet-manager:v0.4.2
    environment:
      - DID_METHOD
      - JOLOCOM_DATABASE_HOST
      - MYSQL_ROOT_PASSWORD
      - RABBITMQ_HOST
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - LOGGING_CONSOLE_ENABLED
      - LOGGING_LEVEL_CONSOLE
      - ENVIRONMENT=dev
      - WAIT_HOSTS=host.docker.internal:3000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    restart: always
    networks:
      - alkemio_dev_net
    command: sh -c "/wait && npm run start"

  redis:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_redis
    hostname: redis
    image: redis:7.0.2
    restart: always
    networks:
      - alkemio_dev_net
    ports:
      - 6379

  guidance_engine:
    container_name: alkemio_dev_guidance_engine
    hostname: guidance-engine
    image: alkemio/guidance-engine:v0.3.0
    restart: always
    volumes:
       - /dev/shm:/dev/shm
       - ~/alkemio/data:${AI_LOCAL_PATH:-/home/alkemio/data}
    networks:
      - alkemio_dev_net
    depends_on:
      rabbitmq:
        condition: "service_healthy"
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - ENVIRONMENT=dev
      - OPENAI_API_KEY
      - OPENAI_API_TYPE
      - OPENAI_API_VERSION
      - OPENAI_API_BASE
      - AI_MODEL_TEMPERATURE
      - AI_MODEL_NAME
      - AI_DEPLOYMENT_NAME
      - AI_EMBEDDINGS_DEPLOYMENT_NAME
      - AI_SOURCE_WEBSITE
      - AI_WEBSITE_REPO
      - AI_LOCAL_PATH

