volumes:
  alkemio_dev_mysql:
  alkemio_dev_postgres:
  tmpvolume:
  chroma-data:
  rabbitmq_data:
    driver: local

networks:
  alkemio_dev_net:

services:
  traefik:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_traefik
    image: traefik:v2.9.6
    restart: always
    ports:
      - 8888:8080
      - 8088:8088
      - 3000:80
      - 3306:3306
      - 5432:5432
      - 8008:8008
      - 4436:4436
      - 4437:4437
      - 1025:1025
      - 5672:5672
      - 15672:15672
      - 6379:6379
      - 8188:8188
    networks:
      - alkemio_dev_net
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ./.build/traefik/
        target: /etc/traefik/

  mysql:
    container_name: alkemio_dev_mysql
    image: mysql:8.3.0
    networks:
      - alkemio_dev_net
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    restart: always
    ports:
      - 3306
    volumes:
      - alkemio_dev_mysql:/var/lib/mysql
      - ./.scripts/schema.sql:/bootstrap_scripts/1.sql
      - ./.scripts/migrations/CSVs:/var/lib/mysql-files/CSVs
      - tmpvolume:/var/lib/mysql-files
    command: --init-file /bootstrap_scripts/1.sql

  kratos-migrate:
    container_name: alkemio_dev_kratos_migrate
    image: oryd/kratos:v1.3.1
    depends_on:
      - mysql
    environment:
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(${DATABASE_HOST}:3306)/kratos?max_conns=20&max_idle_conns=4
    restart: on-failure
    networks:
      - alkemio_dev_net
    volumes:
      - type: bind
        source: ./.build/ory/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos:
    container_name: alkemio_dev_kratos
    image: oryd/kratos:v1.3.1
    depends_on:
      - kratos-migrate
    ports:
      - 4433
      - 4434
    restart: unless-stopped
    environment:
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(${DATABASE_HOST}:3306)/kratos?max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    networks:
      - alkemio_dev_net
    volumes:
      - type: bind
        source: ./.build/ory/kratos
        target: /etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  kratos-admin-ui:
    image: ghcr.io/dfoxg/kratos-admin-ui:v2.5.0
    ports:
      - 8080
    restart: unless-stopped
    environment:
      - KRATOS_ADMIN_URL=http://kratos:4434
      - KRATOS_PUBLIC_URL=http://kratos:4433
    networks:
      - alkemio_dev_net

  oathkeeper:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_oathkeeper
    image: oryd/oathkeeper:v0.38.19-beta.1
    restart: always
    depends_on:
      - kratos
    ports:
      - 4455
      - 4456
    environment:
      - LOG_LEVEL=debug
    networks:
      - alkemio_dev_net
    volumes:
      - ./.build/ory/oathkeeper:/etc/config/oathkeeper
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"

  mailslurper:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_kratos_mailslurper
    image: oryd/mailslurper:latest-smtps
    restart: always
    ports:
      - 4436
      - 4437
      - 1025
    networks:
      - alkemio_dev_net

  synapse:
    container_name: alkemio_dev_synapse
    image: matrixdotorg/synapse:v1.132.0
    depends_on:
      - postgres
    restart: always
    environment:
      - SYNAPSE_NO_TLS=true
      - SYNAPSE_ENABLE_REGISTRATION=true
      - SYNAPSE_HOMESERVER_NAME
      - SYNAPSE_SERVER_URL
      - SYNAPSE_SERVER_SHARED_SECRET
    networks:
      - alkemio_dev_net
    ports:
      - 8008
    volumes:
      - type: bind
        source: ./.build/synapse
        target: /data

  postgres:
    container_name: alkemio_dev_postgres
    image: postgres:17.5
    networks:
      - alkemio_dev_net
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C --lc-ctype=C
    restart: always
    ports:
      - 5432
    volumes:
      - alkemio_dev_postgres:/var/lib/postgresql/data

  synapse-admin:
    container_name: alkemio_dev_synapse_admin
    hostname: synapse-admin
    image: awesometechnologies/synapse-admin:0.8.1
    restart: always
    networks:
      - alkemio_dev_net
    ports:
      - 80

  rabbitmq:
    container_name: alkemio_dev_rabbitmq
    image: rabbitmq:3.9.13-management
    restart: always
    networks:
      - alkemio_dev_net
    ports:
      - 5672
      - 15672
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_DEFAULT_USER=alkemio-admin
      - RABBITMQ_DEFAULT_PASS=alkemio!
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    command:
      [
        'bash',
        '-c',
        'chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server --hostname rmq',
      ]

  notification:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_notifications
    hostname: notifications
    image: alkemio/notifications:v0.26.0
    platform: linux/amd64
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - LOGGING_CONSOLE_ENABLED
      - LOGGING_LEVEL_CONSOLE
      - EMAIL_SMTP_HOST
      - EMAIL_MULTI_PROVIDER_STRATEGY
      - EMAIL_SMTP_SECURE
      - EMAIL_SMTP_PORT
      - EMAIL_SMTP_USER
      - EMAIL_SMTP_PASSWORD
      - ENVIRONMENT=dev
      - ALKEMIO_SERVER_ENDPOINT
      - ALKEMIO_WEBCLIENT_ENDPOINT
      - KRATOS_API_PUBLIC_ENDPOINT
      - SERVICE_ACCOUNT_USERNAME
      - SERVICE_ACCOUNT_PASSWORD
      - WAIT_HOSTS=host.docker.internal:3000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - EMAIL_FROM
      - EMAIL_FROM_NAME
    restart: always
    networks:
      - alkemio_dev_net
    command: sh -c "/wait && npm run start"

  matrix-adapter:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_matrix_adapter
    hostname: matrix-adapter
    image: alkemio/matrix-adapter:v0.7.2
    platform: linux/amd64
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - SYNAPSE_ADMIN_USERNAME
      - SYNAPSE_HOMESERVER_NAME
      - SYNAPSE_SERVER_URL
      - SYNAPSE_SERVER_SHARED_SECRET
      - SYNAPSE_SERVER_NAME
      - LOGGING_CONSOLE_ENABLED
      - LOGGING_LEVEL_CONSOLE
      - ENVIRONMENT=dev
      - WAIT_HOSTS=host.docker.internal:3000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    restart: always
    networks:
      - alkemio_dev_net
    command: sh -c "/wait && npm run start"

  redis:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_dev_redis
    hostname: redis
    image: redis:7.0.2
    restart: always
    networks:
      - alkemio_dev_net
    ports:
      - 6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8381:8081
    networks:
      - alkemio_dev_net
    depends_on:
      - redis

  whiteboard-collaboration:
    container_name: alkemio_dev_whiteboard_collaboration
    hostname: whiteboard-collaboration
    image: alkemio/whiteboard-collaboration-service:v0.6.1
    platform: linux/amd64
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - LOGGING_CONSOLE_ENABLED
      - LOGGING_LEVEL_CONSOLE
      - ENVIRONMENT=dev
    restart: always
    networks:
      - alkemio_dev_net
    ports:
      - 4002

  file-service:
    container_name: alkemio_dev_file_service
    hostname: file-service
    image: alkemio/file-service:v0.1.2
    platform: linux/amd64
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - LOGGING_CONSOLE_ENABLED
      - LOGGING_LEVEL_CONSOLE
      - ENVIRONMENT=dev
      - LOCAL_STORAGE_PATH
    restart: always
    volumes:
      - ../server/.storage:${LOCAL_STORAGE_PATH}
    networks:
      - alkemio_dev_net
    ports:
      - 4003

  collaborative-document:
    container_name: alkemio_dev_collaborative-document
    hostname: collaborative-document
    image: alkemio/collaborative-document-service:v0.0.1
    platform: linux/amd64
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - LOGGING_CONSOLE_ENABLED
      - LOGGING_LEVEL_CONSOLE
      - ENVIRONMENT=dev
    restart: always
    networks:
      - alkemio_dev_net
    ports:
      - 4004
