apiVersion: v1
kind: Service
metadata:
  name: alkemio-server-service

spec:
  ports:
    - protocol: TCP
      name: graphql
      port: 4000
    - protocol: TCP
      name: socket-io
      port: 4001
  selector:
    app: alkemio-server
