export enum ChallengeDisplayLocation {
  CONTRIBUTE = 'CONTRIBUTE_1',
  CONTRIBUTE_RIGHT = 'CONTRIBUTE_2',
  OPPORTUNITIES_LEFT = 'OPPORTUNITIES_1',
  OPPORTUNITIES_RIGHT = 'OPPORTUNITIES_2',
  HOME_RIGHT = 'HOME_RIGHT',
}
