export enum SubspaceCalloutGroup {
  HOME_LEFT = 'HOME_1',
  HOME_RIGHT = 'HOME_2',
  CONTRIBUTE_LEFT = 'CONTRIBUTE_1',
  CONTRIBUTE_RIGHT = 'CONTRIBUTE_2',
  SUBSPACES_LEFT = 'SUBSPACES_1',
  SUBSPACES_RIGHT = 'SUBSPACES_2',
}
