# Weekly CronJob to prune orphaned packages from the shared pnpm store PVC.
# Deploy in the same namespace as the ARC AutoScalingRunnerSet.
# Must use the same nodeSelector as runner pods to access the RWO PVC.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pnpm-store-prune
  labels:
    app.kubernetes.io/component: runner-cache-maintenance
    app.kubernetes.io/part-of: arc-runner-set
spec:
  schedule: "0 3 * * 0"  # Weekly, Sunday 3:00 AM UTC
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: "<runner-node-name>"  # MUST match runner nodeSelector
          volumes:
            - name: pnpm-store-cache
              persistentVolumeClaim:
                claimName: arc-pnpm-store
          containers:
            - name: prune
              image: node:22-bookworm-slim
              command:
                - sh
                - -c
                - |
                  corepack enable
                  corepack prepare pnpm@10.17.1 --activate
                  echo "Store path: $(pnpm store path)"
                  echo "Store size before prune:"
                  du -sh /opt/cache/pnpm-store || true
                  pnpm store prune
                  echo "Store size after prune:"
                  du -sh /opt/cache/pnpm-store || true
              env:
                - name: npm_config_store_dir
                  value: "/opt/cache/pnpm-store"
              volumeMounts:
                - name: pnpm-store-cache
                  mountPath: /opt/cache/pnpm-store
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
          restartPolicy: OnFailure
