/**
 * Stable reason codes of the Form callout framing, carried in
 * `ValidationException.details.code` (never in the message) so clients can
 * localize them. Details may also carry `questionIDs`; they NEVER carry answer
 * text.
 */
export const CalloutFormErrorCode = {
  // submit
  CALLOUT_NOT_PUBLISHED: 'CALLOUT_NOT_PUBLISHED',
  FORM_CLOSED: 'FORM_CLOSED',
  FORM_VISIBILITY_CHANGED: 'FORM_VISIBILITY_CHANGED',
  FORM_RESPONSE_ALREADY_EXISTS: 'FORM_RESPONSE_ALREADY_EXISTS',
  FORM_ANSWER_REQUIRED: 'FORM_ANSWER_REQUIRED',
  FORM_ANSWER_TOO_LONG: 'FORM_ANSWER_TOO_LONG',
  FORM_ANSWER_UNKNOWN_QUESTION: 'FORM_ANSWER_UNKNOWN_QUESTION',
  FORM_ANSWER_DUPLICATE_QUESTION: 'FORM_ANSWER_DUPLICATE_QUESTION',
  FORM_ANSWER_TYPE_MISMATCH: 'FORM_ANSWER_TYPE_MISMATCH',
  FORM_ANSWER_INVALID_OPTION: 'FORM_ANSWER_INVALID_OPTION',
  FORM_ANSWER_SELECTION_COUNT: 'FORM_ANSWER_SELECTION_COUNT',
  // definition
  FORM_QUESTIONS_COUNT: 'FORM_QUESTIONS_COUNT',
  FORM_OPTIONS_COUNT: 'FORM_OPTIONS_COUNT',
  FORM_OPTIONS_DUPLICATE: 'FORM_OPTIONS_DUPLICATE',
  FORM_UNKNOWN_QUESTION_ID: 'FORM_UNKNOWN_QUESTION_ID',
  FORM_UNKNOWN_OPTION_ID: 'FORM_UNKNOWN_OPTION_ID',
  FORM_QUESTION_TYPE_LOCKED: 'FORM_QUESTION_TYPE_LOCKED',
  FORM_VISIBILITY_WIDENING_BLOCKED: 'FORM_VISIBILITY_WIDENING_BLOCKED',
  FORM_RESPONSE_MODE_SWITCH_BLOCKED: 'FORM_RESPONSE_MODE_SWITCH_BLOCKED',
  // placement
  FORM_FRAMING_NOT_ALLOWED: 'FORM_FRAMING_NOT_ALLOWED',
  FORM_FRAMING_FIXED_KIND: 'FORM_FRAMING_FIXED_KIND',
  FORM_TRANSFER_NOT_ALLOWED: 'FORM_TRANSFER_NOT_ALLOWED',
} as const;

export type CalloutFormErrorCodeValue =
  (typeof CalloutFormErrorCode)[keyof typeof CalloutFormErrorCode];
