export const URL_PATHS = {
  HOME: 'home',
  USER: 'user',
  ADMIN: 'admin',
  VIRTUAL_CONTRIBUTOR: 'vc',
  ORGANIZATION: 'organization',
  INNOVATION_LIBRARY: 'innovation-library',
  INNOVATION_PACKS: 'innovation-packs',
  INNOVATION_HUBS: 'innovation-hubs',
  CHALLENGES: 'challenges',
  OPPORTUNITIES: 'opportunities',
  COLLABORATION: 'collaboration',
  CONTRIBUTE: 'contribute',
  POSTS: 'posts',
  WHITEBOARDS: 'whiteboards',
  FORUM: 'forum',
  SPACE_EXPLORER: 'spaces',
  DISCUSSION: 'discussion',
  CALENDAR: 'calendar',
  KNOWLEDGE_BASE: 'knowledge-base',
  SETTINGS: 'settings',
  TEMPLATES: 'templates',
} as const;
