import { MigrationInterface, QueryRunner } from "typeorm";

export class CommunityPolls1772569123375 implements MigrationInterface {
    name = 'CommunityPolls1772569123375'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "credential" DROP CONSTRAINT "FK_credential_actorId"`);
        await queryRunner.query(`ALTER TABLE "actor" DROP CONSTRAINT "FK_actor_profileId"`);
        await queryRunner.query(`ALTER TABLE "actor" DROP CONSTRAINT "FK_actor_authorizationId"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_user_actor_id"`);
        await queryRunner.query(`ALTER TABLE "invitation" DROP CONSTRAINT "FK_invitation_invitedActorId"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_organization_actor_id"`);
        await queryRunner.query(`ALTER TABLE "space" DROP CONSTRAINT "FK_space_actor_id"`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" DROP CONSTRAINT "FK_virtual_contributor_actor_id"`);
        await queryRunner.query(`ALTER TABLE "account" DROP CONSTRAINT "FK_account_actor_id"`);
        await queryRunner.query(`ALTER TABLE "in_app_notification" DROP CONSTRAINT "FK_notification_contributor_actor"`);
        await queryRunner.query(`ALTER TABLE "conversation_membership" DROP CONSTRAINT "FK_conversation_membership_actorId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_credential_actorId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_actor_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_actor_profileId"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_actor_nameID_user"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_actor_nameID_organization"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_actor_nameID_virtual_contributor"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_actor_nameID_account"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_in_app_notification_contributorActorId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_conversation_membership_actorId"`);
        await queryRunner.query(`CREATE TABLE "poll_option" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "updatedDate" TIMESTAMP NOT NULL DEFAULT now(), "version" integer NOT NULL, "text" character varying(512) NOT NULL, "sortOrder" integer NOT NULL, "pollId" uuid, CONSTRAINT "UQ_498bbf02ebeb7a9017866813347" UNIQUE ("pollId", "sortOrder"), CONSTRAINT "PK_5fdd46d449ddcc8201aed9b5a1b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "poll_vote" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "updatedDate" TIMESTAMP NOT NULL DEFAULT now(), "version" integer NOT NULL, "createdBy" uuid NOT NULL, "selectedOptionIds" jsonb NOT NULL, "pollId" uuid, CONSTRAINT "UQ_c3a1e0d8319f92349a8eafc4d5f" UNIQUE ("createdBy", "pollId"), CONSTRAINT "PK_fd002d371201c472490ba89c6a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "poll" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "updatedDate" TIMESTAMP NOT NULL DEFAULT now(), "version" integer NOT NULL, "title" character varying(512) NOT NULL, "status" character varying(128) NOT NULL, "settings" jsonb NOT NULL, "deadline" TIMESTAMP, "authorizationId" uuid, CONSTRAINT "REL_0f5c276b165d753be456719497" UNIQUE ("authorizationId"), CONSTRAINT "PK_03b5cf19a7f562b231c3458527e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "callout_framing" ADD "pollId" uuid`);
        await queryRunner.query(`ALTER TABLE "callout_framing" ADD CONSTRAINT "UQ_1befc5c804ba6c5eb3eb713282e" UNIQUE ("pollId")`);
        await queryRunner.query(`ALTER TABLE "actor" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "actor" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."actor_type_enum"`);
        await queryRunner.query(`ALTER TABLE "actor" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "actor" ADD CONSTRAINT "UQ_a2afa3851ea733de932251b3a1f" UNIQUE ("authorizationId")`);
        await queryRunner.query(`ALTER TABLE "actor" ADD CONSTRAINT "UQ_5b434d551bb69f49f3beb53955d" UNIQUE ("profileId")`);
        await queryRunner.query(`ALTER TABLE "room" ALTER COLUMN "vcData" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "homeSpace" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "accountID" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "rowId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "firstName" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "lastName" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "email" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "serviceProfile" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "accountID" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "settings" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "rowId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "legalEntityName" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "domain" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "website" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "contactEmail" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "rowId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "settings" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "platformRolesAccess" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "level" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "sortOrder" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "sortOrder" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "visibility" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "rowId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "settings" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "platformSettings" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "aiPersonaID" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "listedInStore" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "searchVisibility" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "dataAccessMode" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "interactionModes" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "bodyOfKnowledgeType" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "account" ALTER COLUMN "baselineLicensePlan" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "in_app_notification"."contributorActorId" IS 'FK to Actor - cascade deletes notification when contributor is deleted'`);
        await queryRunner.query(`CREATE INDEX "IDX_01cf61a0048fa466394a9e47c2" ON "conversation_membership" ("actorId") `);
        await queryRunner.query(`ALTER TABLE "credential" ADD CONSTRAINT "FK_f4a4d364457d7cb4c31a0a64b58" FOREIGN KEY ("actorId") REFERENCES "actor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actor" ADD CONSTRAINT "FK_a2afa3851ea733de932251b3a1f" FOREIGN KEY ("authorizationId") REFERENCES "authorization_policy"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actor" ADD CONSTRAINT "FK_5b434d551bb69f49f3beb53955d" FOREIGN KEY ("profileId") REFERENCES "profile"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "poll_option" ADD CONSTRAINT "FK_a1200fcfcdab6145351545f26ea" FOREIGN KEY ("pollId") REFERENCES "poll"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "poll_vote" ADD CONSTRAINT "FK_99f9db6d3dae2a0aebebbf8e10a" FOREIGN KEY ("pollId") REFERENCES "poll"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "poll_vote" ADD CONSTRAINT "FK_poll_vote_createdBy_user" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "poll" ADD CONSTRAINT "FK_0f5c276b165d753be4567194977" FOREIGN KEY ("authorizationId") REFERENCES "authorization_policy"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "callout_framing" ADD CONSTRAINT "FK_1befc5c804ba6c5eb3eb713282e" FOREIGN KEY ("pollId") REFERENCES "poll"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation" ADD CONSTRAINT "FK_3901850cc35d37a2f47c119cae6" FOREIGN KEY ("invitedActorId") REFERENCES "actor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation" ADD CONSTRAINT "FK_82cb26926bb13032087af2b116a" FOREIGN KEY ("createdBy") REFERENCES "actor"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "in_app_notification" ADD CONSTRAINT "FK_48cd51e911d1d7e13661ba4a05b" FOREIGN KEY ("contributorActorId") REFERENCES "actor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "in_app_notification" DROP CONSTRAINT "FK_48cd51e911d1d7e13661ba4a05b"`);
        await queryRunner.query(`ALTER TABLE "invitation" DROP CONSTRAINT "FK_82cb26926bb13032087af2b116a"`);
        await queryRunner.query(`ALTER TABLE "invitation" DROP CONSTRAINT "FK_3901850cc35d37a2f47c119cae6"`);
        await queryRunner.query(`ALTER TABLE "callout_framing" DROP CONSTRAINT "FK_1befc5c804ba6c5eb3eb713282e"`);
        await queryRunner.query(`ALTER TABLE "poll" DROP CONSTRAINT "FK_0f5c276b165d753be4567194977"`);
        await queryRunner.query(`ALTER TABLE "poll_vote" DROP CONSTRAINT "FK_poll_vote_createdBy_user"`);
        await queryRunner.query(`ALTER TABLE "poll_vote" DROP CONSTRAINT "FK_99f9db6d3dae2a0aebebbf8e10a"`);
        await queryRunner.query(`ALTER TABLE "poll_option" DROP CONSTRAINT "FK_a1200fcfcdab6145351545f26ea"`);
        await queryRunner.query(`ALTER TABLE "actor" DROP CONSTRAINT "FK_5b434d551bb69f49f3beb53955d"`);
        await queryRunner.query(`ALTER TABLE "actor" DROP CONSTRAINT "FK_a2afa3851ea733de932251b3a1f"`);
        await queryRunner.query(`ALTER TABLE "credential" DROP CONSTRAINT "FK_f4a4d364457d7cb4c31a0a64b58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01cf61a0048fa466394a9e47c2"`);
        await queryRunner.query(`COMMENT ON COLUMN "in_app_notification"."contributorActorId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "account" ALTER COLUMN "baselineLicensePlan" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "bodyOfKnowledgeType" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "interactionModes" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "dataAccessMode" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "searchVisibility" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "listedInStore" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "aiPersonaID" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "platformSettings" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "settings" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ALTER COLUMN "rowId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "visibility" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "sortOrder" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "sortOrder" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "level" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "platformRolesAccess" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "settings" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ALTER COLUMN "rowId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "contactEmail" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "website" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "domain" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "legalEntityName" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "rowId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "settings" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization" ALTER COLUMN "accountID" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "serviceProfile" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "email" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "lastName" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "firstName" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "rowId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "accountID" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_settings" ALTER COLUMN "homeSpace" SET DEFAULT '{"spaceID": null, "autoRedirect": false}'`);
        await queryRunner.query(`ALTER TABLE "room" ALTER COLUMN "vcData" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "actor" DROP CONSTRAINT "UQ_5b434d551bb69f49f3beb53955d"`);
        await queryRunner.query(`ALTER TABLE "actor" DROP CONSTRAINT "UQ_a2afa3851ea733de932251b3a1f"`);
        await queryRunner.query(`ALTER TABLE "actor" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."actor_type_enum" AS ENUM('user', 'organization', 'virtual-contributor', 'space', 'account')`);
        await queryRunner.query(`ALTER TABLE "actor" ADD "type" "public"."actor_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "actor" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "callout_framing" DROP CONSTRAINT "UQ_1befc5c804ba6c5eb3eb713282e"`);
        await queryRunner.query(`ALTER TABLE "callout_framing" DROP COLUMN "pollId"`);
        await queryRunner.query(`DROP TABLE "poll"`);
        await queryRunner.query(`DROP TABLE "poll_vote"`);
        await queryRunner.query(`DROP TABLE "poll_option"`);
        await queryRunner.query(`CREATE INDEX "IDX_conversation_membership_actorId" ON "conversation_membership" ("actorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_in_app_notification_contributorActorId" ON "in_app_notification" ("contributorActorId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_actor_nameID_account" ON "actor" ("nameID") WHERE (type = 'account'::actor_type_enum)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_actor_nameID_virtual_contributor" ON "actor" ("nameID") WHERE (type = 'virtual-contributor'::actor_type_enum)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_actor_nameID_organization" ON "actor" ("nameID") WHERE (type = 'organization'::actor_type_enum)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_actor_nameID_user" ON "actor" ("nameID") WHERE (type = 'user'::actor_type_enum)`);
        await queryRunner.query(`CREATE INDEX "IDX_actor_profileId" ON "actor" ("profileId") `);
        await queryRunner.query(`CREATE INDEX "IDX_actor_type" ON "actor" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_credential_actorId" ON "credential" ("actorId") `);
        await queryRunner.query(`ALTER TABLE "conversation_membership" ADD CONSTRAINT "FK_conversation_membership_actorId" FOREIGN KEY ("actorId") REFERENCES "actor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "in_app_notification" ADD CONSTRAINT "FK_notification_contributor_actor" FOREIGN KEY ("contributorActorId") REFERENCES "actor"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account" ADD CONSTRAINT "FK_account_actor_id" FOREIGN KEY ("id") REFERENCES "actor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "virtual_contributor" ADD CONSTRAINT "FK_virtual_contributor_actor_id" FOREIGN KEY ("id") REFERENCES "actor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "space" ADD CONSTRAINT "FK_space_actor_id" FOREIGN KEY ("id") REFERENCES "actor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_organization_actor_id" FOREIGN KEY ("id") REFERENCES "actor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation" ADD CONSTRAINT "FK_invitation_invitedActorId" FOREIGN KEY ("invitedActorId") REFERENCES "actor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_user_actor_id" FOREIGN KEY ("id") REFERENCES "actor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actor" ADD CONSTRAINT "FK_actor_authorizationId" FOREIGN KEY ("authorizationId") REFERENCES "authorization_policy"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actor" ADD CONSTRAINT "FK_actor_profileId" FOREIGN KEY ("profileId") REFERENCES "profile"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credential" ADD CONSTRAINT "FK_credential_actorId" FOREIGN KEY ("actorId") REFERENCES "actor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
