CREATE DATABASE IF NOT EXISTS alkemio;
CREATE DATABASE IF NOT EXISTS jolocom;
CREATE DATABASE IF NOT EXISTS kratos;
SET sql_mode = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
