name: Build & Deploy to Dev on AWS

on:
  workflow_dispatch:

env:
  ECR_REGISTRY: ${{ secrets.ECR_DEV_TEST_REGISTRY }}
  ECR_REPOSITORY: alkemio-server
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_DEV }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: "Apply server migration"
        uses: actions/checkout@v3.0.2

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA_DEMO }}

      - uses: azure/setup-kubectl@v3
        with:
          version: "v1.22.0" # default is latest stable, fixing it to a compatible version
        id: install

      - name: Migrate database
        run: |
          kubectl delete job alkemio-server-migration
          kubectl create job --from=cronjob/alkemio-server-migration alkemio-server-migration-job

  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_TEST_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_TEST_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - run: |
          docker build -f Dockerfile . -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: deploy to cluster
        uses: kodermax/kubectl-aws-eks@master
        with:
          args: set image deployment/$ECR_REPOSITORY-deployment $ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: verify deployment
        uses: kodermax/kubectl-aws-eks@master
        with:
          args: rollout status deployment/$ECR_REPOSITORY-deployment
