name: Build & Deploy to Dev

on:
  push:
    branches: [server-1848]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CRED_K8S_NEW }}

      - name: 'Build image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Push image'
        run: |
          docker build -f Dockerfile . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-server:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-server:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-server:${{ github.sha }}
  migrate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CRED_K8S_NEW }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          resource-group: ${{ secrets.RESOURCE_GROUP_K8S }}

      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: alkemio-server-secret

      - uses: azure/setup-kubectl@v3
        with:
          version: "v1.22.0" # default is latest stable, fixing it to a compatible version
        id: install

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/26-server-migration.yaml
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-server:${{ github.sha }}
          imagepullsecrets: |
            alkemio-server-secret

      - name: Delete old job
        continue-on-error: true
        run: |
          kubectl delete job alkemio-server-migration

      - name: Create migration job
        run: |
          kubectl create job --from=cronjob/alkemio-server-migration alkemio-server-migration-job

  deploy:
    needs: migrate
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CRED_K8S_NEW }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          resource-group: ${{ secrets.RESOURCE_GROUP_K8S }}

      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: alkemio-server-secret

      - uses: azure/setup-kubectl@v3
        with:
          version: "v1.22.0" # default is latest stable, fixing it to a compatible version
        id: install

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/25-server-deployment-dev.yaml
            manifests/30-server-service.yaml
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-server:${{ github.sha }}
          imagepullsecrets: |
            alkemio-server-secret