name: Build & Deploy to Test on AWS

on:
  workflow_dispatch:

env:
  ECR_REGISTRY: ${{ secrets.ECR_DEV_TEST_REGISTRY }}
  ECR_REPOSITORY: alkemio-server
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_TEST }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_TEST_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_TEST_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - run: |
          docker build -f Dockerfile . -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: deploy to cluster
        uses: kodermax/kubectl-aws-eks@master
        with:
          args: set image deployment/$ECR_REPOSITORY-deployment $ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: verify deployment
        uses: kodermax/kubectl-aws-eks@master
        with:
          args: rollout status deployment/$ECR_REPOSITORY-deployment
