name: Docker Image CI for test infra

on:
  workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -f Dockerfile . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/ct-server:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/ct-server:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/ct-server:${{ github.sha }}
        - uses: Azure/aks-set-context@v1
          with:
            creds: ${{ secrets.AZURE_CRED_K8S_TEST }}
            cluster-name: ${{ secrets.CLUSTER_NAME_TEST }}
            resource-group: ${{ secrets.RESOURCE_GROUP_K8S_TEST }}

        - uses: Azure/k8s-create-secret@v1
          with:
            container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
            container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            secret-name: ct-server-secret

        - uses: Azure/k8s-deploy@v1
          with:
            manifests: |
              manifests/25-server-deployment.yaml
              manifests/30-server-service.yaml
            images: |
              ${{ secrets.REGISTRY_LOGIN_SERVER }}/ct-server:${{ github.sha }}
            imagepullsecrets: |
              ct-server-secret
