name: Test Release

on:
  release:
    types: [published]
  push:
    branches: [server-1335]
jobs:
  trigger-e2e-tests-travis-ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY: alkem-io/test-suites
    steps:
      - name: Run e2e Tests
        uses: travis-ci/actions@master
        env:
          TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
          GITHUB_REPOSITORY: alkem-io/test-suites
