name: Test Release

on:
  release:
    types: [published]
  push:
    branches: [server-1335]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: alkem-io/test-suites
          token: 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
      - name: Run .travis.yml build script
        uses: ktomk/run-travis-yml@v1
