name: Test Release

on:
  release:
    types: [published]
  push:
    branches: [server-1335]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: alkem-io/test-suites
          token: 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
      - name: Run .travis.yml build script
        uses: ktomk/run-travis-yml@v1
