import { registerEnumType } from '@nestjs/graphql';

export enum AuthorizationPolicyType {
  AGENT = 'agent',
  CALLOUT = 'callout',
  CALLOUTS_SET = 'callouts-set',
  CALLOUT_CONTRIBUTION = 'callout-contribution',
  CALLOUT_FRAMING = 'callout-framing',
  COLLABORATION = 'collaboration',
  INNOVATION_FLOW = 'innovation-flow',
  INNOVATION_HUB = 'innovation-hub',
  INNOVATION_PACK = 'innovation-pack',
  LINK = 'link',
  POST = 'post',
  WHITEBOARD = 'whiteboard',
  KNOWLEDGE_BASE = 'knowledge-base',
  PREFERENCE = 'preference',
  PREFERENCE_SET = 'preference-set',
  PROFILE = 'profile',
  REFERENCE = 'reference',
  TAGSET = 'tagset',
  VISUAL = 'visual',
  COMMUNICATION = 'communication',
  ROOM = 'room',
  AI_PERSONA = 'ai-persona',
  AI_SERVER = 'ai-server',
  APPLICATION = 'application',
  ROLE_SET = 'role-set',
  COMMUNITY = 'community',
  COMMUNITY_GUIDELINES = 'community-guidelines',
  INVITATION = 'invitation',
  FORUM = 'forum',
  PLATFORM = 'platform',
  DISCUSSION = 'discussion',
  USER = 'user',
  USER_GROUP = 'user-group',
  ACTOR = 'actor',
  ACTOR_GROUP = 'actor-group',
  ORGANIZATION = 'organization',
  ORGANIZATION_VERIFICATION = 'organization-verification',
  CONTEXT = 'context',
  ECOSYSTEM_MODEL = 'ecosystem-model',
  VIRTUAL_CONTRIBUTOR = 'virtual-contributor',
  SPACE = 'space',
  SPACE_ABOUT = 'space-about',
  ACCOUNT = 'account',
  DOCUMENT = 'document',
  STORAGE_AGGREGATOR = 'storage-aggregator',
  STORAGE_BUCKET = 'storage-bucket',
  TEMPLATE = 'template',
  TEMPLATES_SET = 'templates-set',
  TEMPLATES_MANAGER = 'templates-manager',
  TEMPLATE_DEFAULT = 'template-default',
  CALENDAR = 'calendar',
  CALENDAR_EVENT = 'calendar-event',
  TIMELINE = 'timeline',
  LIBRARY = 'library',
  IN_MEMORY = 'in-memory',
  LICENSING = 'licensing',
  LICENSE = 'license',
  LICENSE_POLICY = 'license-policy',
  UNKNOWN = 'unknown',
  AI_PERSONA_SERVICE = 'ai-persona-service',
}

registerEnumType(AuthorizationPolicyType, {
  name: 'AuthorizationPolicyType',
});
