import { registerEnumType } from '@nestjs/graphql';

export enum CalloutDisplayLocation {
  COMMON_HOME_TOP = 'HOME_0',
  COMMON_HOME_LEFT = 'HOME_1',
  COMMON_HOME_RIGHT = 'HOME_2',
  COMMON_KNOWLEDGE_RIGHT = 'KNOWLEDGE',

  SPACE_COMMUNITY_LEFT = 'COMMUNITY_1',
  SPACE_COMMUNITY_RIGHT = 'COMMUNITY_2',
  SPACE_CHALLENGES_LEFT = 'CHALLENGES_1',
  SPACE_CHALLENGES_RIGHT = 'CHALLENGES_2',

  CHALLENGE_CONTRIBUTE = 'CONTRIBUTE_1',
  CHALLENGE_CONTRIBUTE_RIGHT = 'CONTRIBUTE_2',
  CHALLENGE_OPPORTUNITIES_LEFT = 'OPPORTUNITIES_1',
  CHALLENGE_OPPORTUNITIES_RIGHT = 'OPPORTUNITIES_2',

  OPPORTUNITY_CONTRIBUTE = 'CONTRIBUTE_1',
  OPPORTUNITY_CONTRIBUTE_RIGHT = 'CONTRIBUTE_2',
}

registerEnumType(CalloutDisplayLocation, {
  name: 'CalloutDisplayLocation',
});
