export enum ConfigurationTypes {
  HOSTING = 'hosting',
  BOOTSTRAP = 'bootstrap',
  MONITORING = 'monitoring',
  SECURITY = 'security',
  IDENTITY = 'identity',
  COMMUNICATIONS = 'communications',
  STORAGE = 'storage',
  PLATFORM = 'platform',
  NOTIFICATIONS = 'notifications',
  MICROSERVICES = 'microservices',
  COLLABORATION = 'collaboration',
  SSI = 'ssi',
  INTEGRATIONS = 'integrations',
  INNOVATION_HUB = 'innovation_hub',
  SEARCH = 'search',
}
