export enum LogContext {
  COMMUNITY = 'community',
  AGENT = 'agent',
  API = 'api',
  AUTH = 'auth',
  AUTH_TOKEN = 'auth_token',
  BOOTSTRAP = 'bootstrap',
  DATA_MGMT = 'data-mgmt',
  CHALLENGES = 'challenges',
  SEARCH = 'search',
  OPPORTUNITY = 'opportunity',
  IPFS = 'ipfs',
  LIFECYCLE = 'lifecycle',
  UNSPECIFIED = 'not_specified',
}
