export enum LogContext {
  CHALLENGES = 'challenges',
  CONTEXT = 'context',
  COMMUNITY = 'community',
  COLLABORATION = 'collaboration',
  AGENT = 'agent',
  API = 'api',
  AUTH = 'auth',
  AUTH_TOKEN = 'auth_token',
  BOOTSTRAP = 'bootstrap',
  DATA_MGMT = 'data-mgmt',
  SEARCH = 'search',
  OPPORTUNITY = 'opportunity',
  IPFS = 'ipfs',
  LIFECYCLE = 'lifecycle',
  UNSPECIFIED = 'not_specified',
}
