export enum LogContext {
  CHALLENGES = 'challenges',
  CONTEXT = 'context',
  COMMUNITY = 'community',
  COMMUNICATION = 'communication',
  COLLABORATION = 'collaboration',
  AGENT = 'agent',
  API = 'api',
  AUTH = 'auth',
  AUTH_TOKEN = 'auth_token',
  BOOTSTRAP = 'bootstrap',
  DATA_MGMT = 'data-mgmt',
  SEARCH = 'search',
  OPPORTUNITY = 'opportunity',
  IPFS = 'ipfs',
  LIFECYCLE = 'lifecycle',
  UNSPECIFIED = 'not_specified',
  NOTIFICATIONS = 'notifications',
  SUBSCRIPTIONS = 'subscriptions',
  SSI = 'ssi',
  WALLET_MANAGER = 'wallet-mgr',
  REQUESTS = 'requests',
  PLATFORM = 'platform',
}
