export enum MessagingQueue {
  WALLET_MANAGER = 'alkemio-wallet-manager',
  NOTIFICATIONS = 'alkemio-notifications',
  SUBSCRIPTION_DISCUSSION_MESSAGE = 'alkemio-subscriptions-discussion-message',
  SUBSCRIPTION_DISCUSSION_UPDATED = 'alkemio-subscriptions-discussion-updated',
  SUBSCRIPTION_UPDATE_MESSAGE = 'alkemio-subscriptions-update-message',
  SUBSCRIPTION_ASPECT_COMMENT = 'alkemio-subscriptions-aspect-comment',
  SUBSCRIPTION_CANVAS_CONTENT = 'alkemio-subscriptions-canvas-content',
  SUBSCRIPTION_PROFILE_VERIFIED_CREDENTIAL = 'alkemio-subscriptions-profile-verified-credential',
  SUBSCRIPTION_CALLOUT_ASPECT_CREATED = 'alkemio-subscriptions-callout-aspect-created',
  SUBSCRIPTION_CALLOUT_MESSAGE_CREATED = 'alkemio-subscriptions-callout-message-created',
  SUBSCRIPTION_OPPORTUNITY_CREATED = 'alkemio-subscriptions-opportunity-created',
  SUBSCRIPTION_CHALLENGE_CREATED = 'alkemio-subscriptions-challenge-created',
  SUBSCRIPTION_ACTIVITY_CREATED = 'alkemio-subscriptions-activity-created',
}
