import { registerEnumType } from '@nestjs/graphql';

export enum NotificationEvent {
  // Platform notifications
  PLATFORM_ADMIN_USER_PROFILE_CREATED = 'PLATFORM_ADMIN_USER_PROFILE_CREATED',
  PLATFORM_ADMIN_USER_PROFILE_REMOVED = 'PLATFORM_ADMIN_USER_PROFILE_REMOVED',
  PLATFORM_ADMIN_GLOBAL_ROLE_CHANGE = 'PLATFORM_ADMIN_GLOBAL_ROLE_CHANGE',
  PLATFORM_ADMIN_SPACE_CREATED = 'PLATFORM_ADMIN_SPACE_CREATED',
  // Non-admin platform notifications
  PLATFORM_FORUM_DISCUSSION_CREATED = 'PLATFORM_FORUM_DISCUSSION_CREATED',
  PLATFORM_FORUM_DISCUSSION_COMMENT = 'PLATFORM_FORUM_DISCUSSION_COMMENT',

  // Organization notifications
  ORGANIZATION_ADMIN_MESSAGE = 'ORGANIZATION_ADMIN_MESSAGE',
  ORGANIZATION_ADMIN_MENTIONED = 'ORGANIZATION_ADMIN_MENTIONED',

  // Space notifications
  SPACE_ADMIN_COMMUNITY_APPLICATION = 'SPACE_ADMIN_COMMUNITY_APPLICATION',
  SPACE_ADMIN_COLLABORATION_CALLOUT_CONTRIBUTION = 'SPACE_ADMIN_COLLABORATION_CALLOUT_CONTRIBUTION',
  SPACE_ADMIN_COMMUNICATION_MESSAGE = 'SPACE_ADMIN_COMMUNICATION_MESSAGE',
  SPACE_ADMIN_COMMUNITY_NEW_MEMBER = 'SPACE_ADMIN_COMMUNITY_NEW_MEMBER',
  SPACE_COMMUNITY_INVITATION_USER_PLATFORM = 'SPACE_COMMUNITY_INVITATION_USER_PLATFORM',
  SPACE_COMMUNICATION_UPDATE = 'SPACE_COMMUNICATION_UPDATE',
  SPACE_COLLABORATION_CALLOUT_PUBLISHED = 'SPACE_COLLABORATION_CALLOUT_PUBLISHED',
  SPACE_COLLABORATION_CALLOUT_COMMENT = 'SPACE_COLLABORATION_CALLOUT_COMMENT',
  SPACE_COLLABORATION_CALLOUT_CONTRIBUTION = 'SPACE_COLLABORATION_CALLOUT_CONTRIBUTION',
  SPACE_COLLABORATION_CALLOUT_CONTRIBUTION_COMMENT = 'SPACE_COLLABORATION_CALLOUT_CONTRIBUTION_COMMENT',

  // User notifications
  USER_SPACE_COMMUNITY_INVITATION = 'USER_SPACE_COMMUNITY_INVITATION',
  USER_SPACE_COMMUNITY_JOINED = 'USER_SPACE_COMMUNITY_JOINED',
  USER_SPACE_COMMUNITY_APPLICATION = 'USER_SPACE_COMMUNITY_APPLICATION',
  USER_SIGN_UP_WELCOME = 'USER_SIGN_UP_WELCOME',
  USER_MENTION = 'USER_MENTION',
  USER_MESSAGE = 'USER_MESSAGE',
  USER_MESSAGE_SENT_COPY = 'USER_MESSAGE_SENT_COPY',
  USER_COMMENT_REPLY = 'USER_COMMENT_REPLY',

  // Virtual contributors
  VIRTUAL_CONTRIBUTOR_ADMIN_SPACE_COMMUNITY_INVITATION = 'VIRTUAL_CONTRIBUTOR_ADMIN_SPACE_COMMUNITY_INVITATION',
}

registerEnumType(NotificationEvent, {
  name: 'NotificationEvent',
});
