import { registerEnumType } from '@nestjs/graphql';

export enum NotificationEventPayload {
  // Platform notifications
  PLATFORM_FORUM_DISCUSSION = 'PLATFORM_FORUM_DISCUSSION',
  PLATFORM_FORUM_DISCUSSION_COMMENT = 'PLATFORM_FORUM_DISCUSSION_COMMENT',
  PLATFORM_USER_PROFILE_REMOVED = 'PLATFORM_USER_PROFILE_REMOVED',
  PLATFORM_GLOBAL_ROLE_CHANGE = 'PLATFORM_GLOBAL_ROLE_CHANGE',

  // Organization notifications
  ORGANIZATION_MESSAGE_DIRECT = 'ORGANIZATION_MESSAGE_DIRECT',
  ORGANIZATION_MESSAGE_ROOM = 'ORGANIZATION_MESSAGE_ROOM',

  // Space notifications
  SPACE = 'SPACE',
  SPACE_COMMUNITY_APPLICATION = 'SPACE_COMMUNITY_APPLICATION',
  SPACE_COMMUNITY_CONTRIBUTOR = 'SPACE_COMMUNITY_CONTRIBUTOR',
  SPACE_COMMUNITY_INVITATION = 'SPACE_COMMUNITY_INVITATION',
  SPACE_COMMUNITY_INVITATION_USER_PLATFORM = 'SPACE_COMMUNITY_INVITATION_USER_PLATFORM',
  SPACE_COMMUNICATION_MESSAGE_DIRECT = 'SPACE_COMMUNICATION_MESSAGE_DIRECT',
  SPACE_COMMUNICATION_UPDATE = 'SPACE_COMMUNICATION_UPDATE',
  SPACE_COLLABORATION_CALLOUT = 'SPACE_COLLABORATION_CALLOUT',
  SPACE_COLLABORATION_CALLOUT_COMMENT = 'SPACE_COLLABORATION_CALLOUT_COMMENT',
  SPACE_COLLABORATION_CALLOUT_POST_COMMENT = 'SPACE_COLLABORATION_CALLOUT_POST_COMMENT',

  // User notifications
  USER = 'USER',
  USER_MESSAGE_DIRECT = 'USER_MESSAGE_DIRECT',
  USER_MESSAGE_ROOM = 'USER_MESSAGE_ROOM',

  // Virtual Contributor related payloads
  VIRTUAL_CONTRIBUTOR = 'VIRTUAL_CONTRIBUTOR',
}

registerEnumType(NotificationEventPayload, {
  name: 'NotificationEventPayload',
});
