export enum ProfileType {
  SPACE = 'SPACE',
  CHALLENGE = 'challenge',
  OPPORTUNITY = 'opportunity',
  INNOVATION_FLOW = 'innovation-flow',
  CALLOUT_FRAMING = 'callout-framing',
  CALLOUT = 'callout',
  POST = 'post',
  WHITEBOARD_RT = 'whiteboard-rt',
  WHITEBOARD = 'whiteboard',
  DISCUSSION = 'discussion',
  ORGANIZATION = 'organization',
  USER_GROUP = 'user-group',
  USER = 'user',
  INNOVATION_HUB = 'innovation-hub',
  EVENT = 'event',
  INNOVATION_PACK = 'innovation-pack',
  CALLOUT_TEMPLATE = 'callout-framing',
  INNOVATION_FLOW_TEMPLATE = 'innovation-flow',
  POST_TEMPLATE = 'post-template',
  WHITEBOARD_TEMPLATE = 'whiteboard-template',
}
