export const RestrictedSpaceNames = [
  /* GROUP | Existing routes see UrlPathBase */
  'home',
  'user',
  'admin',
  'vc',
  'organization',
  'documentation',
  'innovation-library',
  'innovation-packs',
  'innovation-hubs',
  'forum',
  'spaces',
  'contributors',
  'about',
  'profile',
  'restricted',
  'docs',
  'contact',

  // Flow routes
  'create-space',

  // Legacy routes
  'landing', // Legacy route that redirects to Welcome site
  'identity', // Legacy route that's not used anymore but is decided to be reserved

  // Reserved routes
  'flows',

  /* GROUP | Technical concerns */
  'root',
  'root-admin',
  'root-user',
  'dashboard',
  'start',
  'login',
  'logout',
  'register',
  'settings',
  'system',
  'error',
  '404',
  '500',
  'help',
  'support',
  'official-support',
  'api',
  'faq',
  'contact-us',
  'feedback',
  'test',
  'null',
  'undefined',
  'graphql',
  'graphql-api',
  'ws',
  'websocket',
  'socket',
  'rest',

  /* GROUP | Ethical and Security Concerns */
  'official',
  'admin-help',
  'moderator',
  'support-team',
  'fake',
  'scam',
  'phishing',
  'report',
  'security',
  'malware',
  'hacker',
  'bitcoin',
  'crypto',
  'money',
  'free',
  'giveaway',
  'auth',
  'oauth',
  'authentication',
  'authorization',
  'identity-verification',
  'callback',
  'validation',
  'validate',
  'confirmation',
  'confirm',
  'verify',
  'verify-email',
  'verify-identity',
  'verify-phone',
  'verify-account',
  'token',
  'access-token',

  /* GROUP | Legal Concerns */
  'terms',
  'privacy',
  'terms-of-service',
  'privacy-policy',
  'cookie-policy',
  'legal-notice',
  'legal-terms',
  'terms-and-conditions',
  'privacy-notice',
  'nda',
  'eula',
  'gdpr',
  'legal',
  'cookie',

  /* GROUP | Alkemio-related */
  'alkemio',
  'alchemy',
  'alkemiofoundation',
  'alkemio-foundation',
  'alkemiobv',
  'alkemio-bv',
  'cherrytwist',
  'create-subspace',
  'create-vc',
  'create-user',
  'create-account',
  'innovation-pack',
  'innovation-hub',
  'space',
  'subspace',
  'virtualcontributor',
  'virtual-contributor',
  'virtual-contributors',
  'org',

  /* GROUP | Reserved for Future Platform Use */
  'official-features',
  'updates',
  'announcements',
  'news',
  'releases',
  'features',
  'guides',
  'resources',
  'workspace',
  'team',
  'project',
  'initiative',
  'partners',
  'community',
  'hub',
  'event',
  'events',
  'office',
  'timeline',
  'calendar',
];
