export enum SpaceReservedName {
  USER = 'user',
  ORGANIZATION = 'organization',
  VIRTUAL_CONTRIBUTOR = 'vc',
  ADMIN = 'admin',
  INNOVATION_LIBRARY = 'innovation-library',
  INNOVATION_PACKS = 'innovation-packs',
  CREATE_SPACE = 'create-space',
  HOME = 'home',
  SPACES = 'spaces',
  CONTRIBUTORS = 'contributors',
  FORUM = 'forum',
  ABOUT = 'about',
  PROFILE = 'profile',
  RESTRICTED = 'restricted',
}
